excerpt_separator: ""
#pygments: true
markdown: kramdown
url: http://mattymaloney.github.io
title: Matty Maloney
email: 
author: Zombie Rot
description: Rotting flesh and evidence of mental and emotional limitations.
paginate: 100
google_analytics:
